name: CI/CD Pipeline for ONEHADA_FE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js 설치 및 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Next.js 프로젝트 디렉토리로 이동
      - name: Change to project directory
        run: cd one-hada

      # .env 파일 생성
      - name: Create env file
        run: |
          cd one-hada
          echo "${{ secrets.ENV_SECRET }}" > .env

      # package-lock.json 생성을 위한 clean install
      - name: Install dependencies
        run: |
          cd one-hada
          rm -rf node_modules
          npm install

      # Next.js 프로젝트 빌드
      - name: Build
        run: |
          cd one-hada
          npm run build

      # 빌드 결과물을 아티팩트로 저장
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: |
            one-hada/.next/
            one-hada/package.json
            one-hada/package-lock.json
            one-hada/public/
            one-hada/.env

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 빌드된 아티팩트 다운로드
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: next-build

      # EC2로 빌드 파일 전송
      - name: Copy build files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: 'next-build/*'
          target: '~/next-temp'
          strip_components: 1

      # EC2 인스턴스에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 기존 배포본 백업
            if [ -d ~/ONE-HADA/one-hada ]; then
              cp -r ~/ONE-HADA/one-hada ~/next-backup
            fi

            # PM2 프로세스 정리
            pm2 delete next-app || true
            pm2 save

            # 새 버전 배포
            rm -rf ~/ONE-HADA/one-hada
            mv ~/next-temp ~/ONE-HADA/one-hada

            # 의존성 설치 및 서비스 시작
            cd ~/ONE-HADA/one-hada
            npm install --omit=dev  # --production 대신 --omit=dev 사용

            # 보안 취약점 수정
            npm audit fix

            # PM2로 서비스 시작
            pm2 start npm --name "next-app" -- start

            # 배포 후 정리
            rm -rf ~/next-backup

            # PM2 프로세스 목록 저장
            pm2 save

            # 서비스 상태 확인
            pm2 list

            # 정상 종료
            exit 0
