name: CI/CD Pipeline for ONEHADA_FE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 프로젝트 디렉토리로 이동
            cd /home/${{ secrets.EC2_USERNAME }}/ONE-HADA/one-hada || exit 1

            # 최신 코드 가져오기
            git fetch origin || exit 1
            git reset --hard origin/main || exit 1

            # 환경변수 설정
            echo "${{ secrets.ENV_SECRET }}" > .env || exit 1

            # 의존성 설치 및 빌드
            npm install || exit 1
            npm run build || exit 1

            # PM2로 앱 실행/재시작
            pm2 list || exit 1
            pm2 restart next-app || pm2 start npm --name "next-app" -- start || exit 1

            # 배포된 애플리케이션 확인 (서버에서 HTTP 요청)
            curl -f http://localhost:3000 || exit 1

            exit 0
