name: CI/CD Pipeline for ONEHADA_FE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 프로젝트 디렉토리로 이동
            cd /home/${{ secrets.EC2_USERNAME }}/ONE-HADA/one-hada

            # 최신 코드 가져오기
            git pull origin main

            # 환경변수 설정
            echo "${{ secrets.ENV_SECRET }}" > .env

            # 의존성 설치 및 빌드
            npm install
            npm run build

            # PM2로 앱 실행/재시작
            pm2 restart next-app 2>/dev/null || pm2 start npm --name "next-app" -- start

            # 완료 메시지 출력
            echo "Deployment completed successfully"
